### ISSUE TITLE
Investigación de Costos

### ISSUE THREAD

**Issue by EdnaEspejo** [EdnaEspejo/Cifras-con-plastilina#1]
Se requiere realizar un levantamiento de información que contenta los costos que tiene la construcción de un hospital, una casa, un colegio, etc.

- [ ] Investigación

**Comment by rzambrano112** [comment]
Se anexa una primera investigación general sobre el tema de levantamiento de información.

**Comment by rzambrano112** [comment]
Se anexa una

**Comment by rzambrano112** [comment]
Se anexa una primera versión del levantamiento de información general de costos.

**Comment by rzambrano112** [comment]
Se anexa archivo.
[Cifras_Plastilina. Investigación.pdf](https://github.com/EdnaEspejo/Cifras-con-plastilina/files/1006142/Cifras_Plastilina.Investigacion.pdf)

**Comment by rzambrano112** [comment]
Se consolidará la información previa rectificación con la misma a partir de un argumento proveniente de una institución publica.

**Comment by rzambrano112** [comment]
Se anexa un archivo del Dane en donde se prescribe que el costo de la construcción de hospitales, casa, bodegas o cualquier bien inmueble esta condicionado por varias variables de acuerdo al terreno, lugar de compra,

**Comment by rzambrano112** [comment]
https://www.dane.gov.co/files/investigaciones/fichas/Ipen.pdf

**Comment by rzambrano112** [comment]
Un caso particular seria este
![image](https://cloud.githubusercontent.com/assets/20976993/26133150/c2e323f8-3a6a-11e7-9890-79ef791eba7e.png)

**Comment by rzambrano112** [comment]
Se cierra issue #1
