### ISSUE TITLE
Diseño de Mockups

### ISSUE THREAD

**Issue by EdnaEspejo** [EdnaEspejo/Cifras-con-plastilina#3]
Se requiere realizar diseño de mockups

- [x] Mockups de interfaz

**Comment by ghost** [comment]
Hola buenas tardes,
a continuación encontraran los mockups propuestos para el proyecto,  si es necesario hacer algún cambio se tomaran en cuenta para el desarrollo final del proyecto. 

[Mockups cifras en plastilina.pdf](https://github.com/EdnaEspejo/Cifras-con-plastilina/files/1012636/Mockups.cifras.en.plastilina.pdf)

**Comment by EdnaEspejo** [comment]
Se hizo el commit correspondiente
